### ISSUE TITLE
License

### ISSUE THREAD

**Issue by josepaiva94** [monstar-lab-oss/nestjs-starter-rest-api#110]
First, thanks for this awesome solid starter project!

I was checking it out to use it but it misses a license, so I'm not sure I can use?

**Comment by josepaiva94** [comment]
Actually, it is in the `package.json` as `MIT`.

I suggest to place it in the root as `LICENSE` file so Github scans it.

**Comment by yashmurty** [comment]
@josepaiva94 CC @war1oc  
Thank you for checking out our starter-kit!
We are happy to hear that you like it.

We have updated the License to be `MIT`, which we already stated in the `package.json` file.

Please let us know if you find anything else that could be improved / is missing. :slightly_smiling_face: 

All the best!
