### ISSUE TITLE
When I run 'start', the database does not automatically generate entity tables.

### ISSUE THREAD

**Issue by MrZsxForJAVA** [monstar-lab-oss/nestjs-starter-rest-api#187]
When I run 'start', the database does not automatically generate entity tables.

**Comment by yashmurty** [comment]
@MrZsxForJAVA 
Thanks for pointing out. 
We currently run the migrations via
`npm run migration:run`
```
"migration:run": "ts-node node_modules/.bin/typeorm migration:run",
```

We will update the README doc to indicate the same, since there is no explanation for this.
Please let us know if you face any more issues. :slightly_smiling_face: 
All the best!
