### ISSUE TITLE
list all users fails with @UseGuards(JwtAuthGuard) 

### ISSUE THREAD

**Issue by vijaykumar1710** [monstar-lab-oss/nestjs-starter-rest-api#418]
list all users api fails to retrieve all the users if the guard is added and throws the `Internal server error`

**Comment by war1oc** [comment]
Hello @vijaykumar1710, can you add more detail such as a stack trace from the console? 
Meanwhile, @ZulfikarAliZihan let's try to see if we can reproduce this issue.

**Comment by vijaykumar1710** [comment]
> Hello @vijaykumar1710, can you add more detail such as a stack trace from the console? Meanwhile, @ZulfikarAliZihan let's try to see if we can reproduce this issue.

console error looks like this 

`{"contextName":"AllExceptionsFilter","ctx":{"ip":"::1","requestID":"fd4382dc-c1b4-42cf-bb7f-4803ce94b9f3","url":"/api/v1/users","user":null},"error":{"details":"","errorName":"InternalException","message":"Internal server error","path":"/api/v1/users","requestId":"fd4382dc-c1b4-42cf-bb7f-4803ce94b9f3","statusCode":500,"timestamp":"2023-12-22T10:42:01.205Z"},"level":"warn","message":"Internal server error","timestamp":"2023-12-22T10:42:01.206Z"}`

**Comment by vijaykumar1710** [comment]
@war1oc @ZulfikarAliZihan  This issue is also re-producible at my end, even if i remove all my changes. This needs to be looked. Only admin should be allowed to see all users list.

**Comment by vijaykumar1710** [comment]
Please order the annotations for the api function as below. It started working.
 ```
@UseGuards(JwtAuthGuard, RolesGuard)
  @Roles(ROLE.ADMIN, ROLE.SUPERADMIN)
  @ApiBearerAuth()
  @UseInterceptors(ClassSerializerInterceptor)
  @Get()
  @ApiOperation({
    summary: 'Get users as a list API',
  })
  @ApiResponse({
    status: HttpStatus.OK,
    type: SwaggerBaseApiResponse([UserOutput]),
  })
  @ApiResponse({
    status: HttpStatus.UNAUTHORIZED,
    type: BaseApiErrorResponse,
  })
```
