### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by mbnoimi** [monstar-lab-oss/nestjs-starter-rest-api#95]
Hi,

Have considered adding multi-tenancy (ex. [nestjs-mtenant](https://github.com/AlexanderC/nestjs-mtenant))?

**Comment by war1oc** [comment]
Hi @mbnoimi,

Multi-tenancy is not part of the starter kit idea that we had to get started with a nest application quickly. However, we may think of a sample multi-tenant implementation in the near future.

**Comment by yashmurty** [comment]
@mbnoimi 
Thank you so much for checking out our project and suggesting possible features that we could include. 

As @war1oc mentioned, we have concluded that `multi-tenancy` is not going to be on our road-map anytime soon.
But if a lot of users ask us about it, we would seriously consider it for sure. 

Currently we are trying to keep the starter-kit as minimal as possible with the sole focus on `REST API` and `Monolithic` structure. 
Soon we would like to kick-off our starter-kits in `GraphQL`, `Micro-services`, etc. 
So please keep an eye out for those as well. 

All the best, and feel free to reach out to us anytime. :smile:
